name: Scrape and Commit Stocks

on:
  push:
    branches:
      - main
  schedule:
    # 5am UK time: 4am UTC (BST), 5am UTC (GMT)
    - cron: "0 4 * * *"
    # 1pm UK time: 12pm UTC (BST), 13pm UTC (GMT)
    - cron: "0 14 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies and Chrome
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

      - name: Run scraper
        run: |
          xvfb-run --auto-servernum python stock_screener_scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stocks.csv
          git commit -m "Update stocks.csv [auto]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
